theme: minima
title: Best country in World
author: V V Krishna
email: myemail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Much visit countries in World.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
